{
 "title": "SQL Server Monitoring",
 "description": "Performance and health metrics for your SQL Servers using WMI Exporter and Prometheus",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "60s" },
   {
    "name": "group",
    "label": "Group",
    "query": {
     "query": "label_values(windows_mssql_collector_duration_seconds, group)"
    }
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(windows_mssql_collector_duration_seconds{group=~\"$group.*\"}, job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(windows_mssql_collector_duration_seconds{group=~\"$group.*\",job=~\"$job.*\"}, instance)"
    }
   },
   {
    "name": "dbinstance",
    "label": "DB Instance",
    "query": {
     "query": "label_values(windows_mssql_genstats_logical_connections{instance=~\"$instance.*\"}, mssql_instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "SRV | General Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "DATABASES HEALTH",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=~\"$instance.*\"}"
    }
   ]
  },
  {
   "title": "DEADLOCKS",
   "type": "stat",
   "description": "**DEADLOCKS**\n\nNumber of lock requests per second that resulted in a deadlock since last restart",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_mssql_genstats_mars_deadlocks{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"}"
    }
   ]
  },
  {
   "title": "RUIG",
   "type": "stat",
   "description": "**RUIG**\n\nNumber of duplicate tempdb recovery unit id generated.",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_mssql_genstats_tempdb_recovery_unit_ids_generated{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"}"
    }
   ]
  },
  {
   "title": "DB LOGICAL CONNECTIONS",
   "type": "stat",
   "description": "**LOGICAL CONNECTIONS**\n\nNumber of logical connections to the system.\n\nThe main purpose of logical connections is to service multiple active result sets (MARS) requests. For MARS requests, every time that an application makes a connection to SQL Server, there may be more than one logical connection that corresponds to a physical connection.\n\nWhen MARS is not used, the ratio between physical and logical connections is 1:1. Therefore, every time that an application makes a connection to SQL Server, logical connections will increase by 1.",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_mssql_genstats_logical_connections{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"}"
    }
   ]
  },
  {
   "title": "NETWORK UTILIZATION",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "  sum(irate(windows_net_bytes_total{instance=~\"$instance.*\"}[$interval])) / sum(windows_net_current_bandwidth_bytes{instance=~\"$instance.*\"}/8) * 100"
    }
   ]
  },
  {
   "title": "STORAGE",
   "type": "gauge",
   "description": "**STORAGE**\n\nShow drive space usage by percentage.",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "label_replace(({__name__=~\"^windows_logical_disk_size_bytes.*\", instance=~\"$instance.*\"} - {__name__=~\"^windows_logical_disk_free_bytes.*\", instance=~\"$instance.*\"}) / {__name__=~\"^windows_logical_disk_size_bytes.*\", instance=~\"$instance.*\"} * 100, \"name\", \"$1\", \"__name__\", \"(.*)\")",
     "legendFormat": "{{ volume }}"
    }
   ]
  },
  {
   "title": "LOGINS-LOGOUTS",
   "type": "bargauge",
   "description": "**LOGINS-LOGOUTS**\n\nTotal number of logins started per second. This does not include pooled connections.\n\nTotal number of logout operations started per second.",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "windows_mssql_genstats_logins{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Logins/sec"
    },
    {
     "expr": "wmi_mssql_genstats_logouts{instance=~\"$instance.*\", exported_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Logouts/sec"
    }
   ]
  },
  {
   "title": "ACTIVE TEMP TABLES",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_mssql_genstats_active_temp_tables{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"}"
    }
   ]
  },
  {
   "title": "LONGEST TRANSACT RUN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_mssql_transactions_longest_transaction_running_seconds{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"}"
    }
   ]
  },
  {
   "title": "tempDB FREE SPACE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_mssql_transactions_tempdb_free_space_bytes{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"}"
    }
   ]
  },
  {
   "title": "LOCK WAITS I/O",
   "type": "stat",
   "description": "**LOCK WAITS I/O**\n\nSQL Trace IO Provider Lock Waits",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_mssql_genstats_sql_trace_io_provider_lock_waits{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"}"
    }
   ]
  },
  {
   "title": "BLOCKS",
   "type": "stat",
   "description": "**LOCK WAITS I/O**\n\nSQL Trace IO Provider Lock Waits",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_mssql_genstats_blocked_processes{instance=~\"$instance.*\",mssql_instance=~\"$dbinstance.*\"}\r\n"
    }
   ]
  },
  {
   "title": "CONNECTIONS RESETS",
   "type": "stat",
   "description": "**CONNECTIONS RESETS**\n\nTotal number of logins started from the connection pool.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_mssql_genstats_connection_resets{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"}"
    }
   ]
  },
  {
   "title": "KPI | CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "**CPU Usage**\n\nShow cpu usage by mode.",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (mode) (irate(windows_cpu_time_total{instance=~\"$instance.*\"}[$interval]))",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "description": "**CPU**\n\nShow CPU usage by percentage.",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(windows_cpu_time_total{instance=~\"$instance.*\", mode=~\"idle.*\"}[$interval])) * 100)"
    }
   ]
  },
  {
   "title": "CPU load per process",
   "type": "graph",
   "description": "**CPU load per process**\n\nShow cpu usage by process.",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "CPU load" }
   ],
   "targets": [
    {
     "expr": "sum by (process) (rate(process_cpu_seconds_total{instance=~\"$instance.*\", process !~\"Idle\"}[$interval]))",
     "legendFormat": "{{ process }}"
    }
   ]
  },
  {
   "title": "System Idle (%)",
   "type": "gauge",
   "description": "**System Idle (%)**\n\nShow CPU system idle by percentage.",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance) (irate(windows_process_cpu_time_total{instance=~\"$instance.*\", process=~\"Idle.*\"}[$interval]))"
    }
   ]
  },
  {
   "title": "SQL CPU (%)",
   "type": "gauge",
   "description": "**SQL CPU (%)**\n\nReturns elapsed time that all of the threads of this process used the processor to execute instructions by mode (privileged, user).",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (instance) (irate(windows_process_cpu_time_total{instance=~\"$instance.*\", process=~\"sql.*\"}[$interval]))"
    }
   ]
  },
  {
   "title": "KPI | Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Physical memory",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(windows_cs_physical_memory_bytes{instance=~\"$instance.*\"} - windows_os_physical_memory_free_bytes{instance=~\"$instance.*\"}) / windows_cs_physical_memory_bytes{instance=~\"$instance.*\"} * 100"
    }
   ]
  },
  {
   "title": "Virtual memory",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(windows_os_virtual_memory_bytes{instance=~\"$instance.*\"} - windows_os_virtual_memory_free_bytes{instance=~\"$instance.*\"}) / windows_os_virtual_memory_bytes{instance=~\"$instance.*\"} * 100"
    }
   ]
  },
  {
   "title": "Used/Target Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_mssql_memmgr_total_server_memory_bytes{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"}"
    }
   ]
  },
  {
   "title": "Free List Stalls/sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_mssql_bufman_free_list_stalls{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"}"
    }
   ]
  },
  {
   "title": "Average commit bytes per process",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg by (process) (windows_process_private_bytes{instance=~\"$instance.*\", process=~\".*\"})",
     "legendFormat": "{{ process }}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_mssql_memmgr_target_server_memory_bytes{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"}"
    }
   ]
  },
  {
   "title": "Memory Used by DB Instance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_mssql_memmgr_stolen_server_memory_bytes{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"}"
    }
   ]
  },
  {
   "title": "Memory Grant Pending",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_mssql_memmgr_pending_memory_grants{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"}"
    }
   ]
  },
  {
   "title": "Memory Lock",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_mssql_memmgr_lock_memory_bytes{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"}"
    }
   ]
  },
  {
   "title": "PLE",
   "type": "stat",
   "description": "**PLE**\n\nIndicates the number of seconds a page will stay in the buffer pool without references.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_mssql_bufman_page_life_expectancy_seconds{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"}"
    }
   ]
  },
  {
   "title": "KPI | I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "PAGE READS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_mssql_bufman_page_reads{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"}"
    }
   ]
  },
  {
   "title": "PAGE WRITES",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_mssql_bufman_page_writes{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"}"
    }
   ]
  },
  {
   "title": "SQL READ I/O",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (mode) (windows_process_io_bytes_total{instance=~\"$instance.*\", mode=\"read\", process=~\"sql.*\"})"
    }
   ]
  },
  {
   "title": "SQL WRITE I/O",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (mode) (windows_process_io_bytes_total{instance=~\"$instance.*\", mode=\"write\", process=~\"sql.*\"})"
    }
   ]
  },
  {
   "title": "NETWORK READ I/O",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (mode) (windows_process_io_bytes_total{instance=~\"$instance.*\", mode=\"read\", process=~\"svchost.*\"})"
    }
   ]
  },
  {
   "title": "NETWORK WRITE I/O",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (mode) (windows_process_io_bytes_total{instance=~\"$instance.*\", mode=\"write\", process=~\"svchost.*\"})"
    }
   ]
  },
  {
   "title": "KPI | Others",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {}
   ]
  },
  {
   "title": "USER CONNECTIONS",
   "type": "gauge",
   "description": "**USER CONNECTIONS**\n\nCounts the number of users currently connected to SQL Server.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "windows_mssql_genstats_user_connections{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"}"
    }
   ]
  },
  {
   "title": "BYTES PER CONNECTION",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (mssql_instance) (windows_mssql_memmgr_connection_memory_bytes{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"})"
    }
   ]
  },
  {
   "title": "DATA FILE SIZE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (mssql_instance) (windows_mssql_databases_data_files_size_bytes{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"})"
    }
   ]
  },
  {
   "title": "LOG USED (%)",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (mssql_instance) (windows_mssql_databases_log_used_percent{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"})"
    }
   ]
  },
  {
   "title": "BACKUP/RESTORE THROUGHPUT",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (mssql_instance) (windows_mssql_databases_backup_restore_operations{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"})"
    }
   ]
  },
  {
   "title": "Performance Counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {}
   ]
  },
  {
   "title": "SQL Server Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "windows_mssql_sqlstats_batch_requests{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Batch Requests/sec"
    },
    {
     "expr": "windows_mssql_genstats_user_connections{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "User Connections"
    },
    {
     "expr": "windows_mssql_genstats_logins{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Logins/sec"
    },
    {
     "expr": "windows_mssql_genstats_logouts{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Logouts/sec"
    },
    {
     "expr": "windows_mssql_sqlstats_sql_compilations{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "SQL Compilations/sec"
    },
    {
     "expr": "windows_mssql_sqlstats_sql_recompilations{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "SQL Re-Compilations/sec"
    },
    {
     "expr": "windows_mssql_genstats_blocked_processes{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Processes blocked"
    }
   ]
  },
  {
   "title": "Databases Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (mssql_instance) (windows_mssql_databases_transactions{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"})",
     "legendFormat": "Transactions/sec"
    },
    {
     "expr": "avg by (mssql_instance) (windows_mssql_databases_write_transactions{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"})",
     "legendFormat": "Write Transactions/sec"
    },
    {
     "expr": "avg by (mssql_instance) (windows_mssql_databases_log_flushes{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"})",
     "legendFormat": "Log Flushes/sec"
    },
    {
     "expr": "avg by (mssql_instance) (windows_mssql_databases_log_flush_wait_seconds{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"})",
     "legendFormat": "Log Flush Wait Time"
    },
    {
     "expr": "avg by (mssql_instance) (windows_mssql_locks_lock_timeouts{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"})",
     "legendFormat": "Lock Timeouts/sec"
    },
    {
     "expr": "avg by (mssql_instance) (windows_mssql_databases_group_commit_stall_seconds{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"})",
     "legendFormat": "Group Stall/sec"
    },
    {
     "expr": "avg by (mssql_instance) (windows_mssql_locks_lock_wait_seconds{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"})",
     "legendFormat": "Lock Waits/sec"
    },
    {
     "expr": "avg by (mssql_instance) (windows_mssql_databases_log_pool_disk_reads{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"})",
     "legendFormat": "Pool Disc/sec"
    }
   ]
  },
  {
   "title": "Buffer Cache - Disk",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "windows_mssql_accessmethods_full_scans{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Full Scans/sec"
    },
    {
     "expr": "windows_mssql_accessmethods_index_searches{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Index Searches/sec"
    },
    {
     "expr": "windows_mssql_accessmethods_page_splits{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Page Splits/sec"
    },
    {
     "expr": "windows_mssql_bufman_page_lookups{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Page lookups/sec"
    },
    {
     "expr": "windows_mssql_bufman_page_reads{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Page reads/sec"
    },
    {
     "expr": "windows_mssql_bufman_page_writes{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Page writes/sec"
    },
    {
     "expr": "windows_mssql_bufman_read_ahead_pages{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Readahead pages/sec"
    },
    {
     "expr": "windows_mssql_bufman_lazywrites{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Lazy writes/sec"
    },
    {
     "expr": "windows_mssql_bufman_checkpoint_pages{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Checkpoint pages/sec"
    }
   ]
  },
  {
   "title": "Memory Manager",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "windows_mssql_memmgr_sql_cache_memory_bytes{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "SQL Cache"
    },
    {
     "expr": "windows_mssql_memmgr_optimizer_memory_bytes{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Optimizer"
    },
    {
     "expr": "windows_mssql_memmgr_log_pool_memory_bytes{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Log Pool"
    },
    {
     "expr": "windows_mssql_memmgr_lock_memory_bytes{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Lock"
    },
    {
     "expr": "windows_mssql_memmgr_database_cache_memory_bytes{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Database Cache"
    },
    {
     "expr": "windows_mssql_memmgr_connection_memory_bytes{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Connection"
    }
   ]
  },
  {
   "title": "Lock Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace({__name__=~\"windows_mssql_locks_lock_requests.*\",instance=~\"$instance.*\"}, \"name\", \"$1\", \"__name__\", \"windows_mssql_locks_lock_requests(.*)\")",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Ratios",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "windows_mssql_accessmethods_page_splits{instance=~\"$instance.*\"}",
     "legendFormat": "Pages split/batch request"
    },
    {
     "expr": "windows_mssql_sqlstats_sql_compilations{instance=~\"$instance.*\"}",
     "legendFormat": "SQL Compilation/batch request"
    },
    {
     "expr": "windows_mssql_bufman_page_reads{instance=~\"$instance.*\"}",
     "legendFormat": "Read-ahead/page read"
    },
    {
     "expr": "windows_mssql_sqlstats_sql_recompilations{instance=~\"$instance.*\"}",
     "legendFormat": "SQL Recompilation/batch request"
    }
   ]
  },
  {
   "title": "Database Size Trend",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Database | Rows Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace({__name__=~\"^windows_mssql_databases_bulk_copy_rows.*\", instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"}, \"db\", \"$1\", \"__name__\", \"(.*)\")",
     "legendFormat": "{{ database }}"
    }
   ]
  },
  {
   "title": "Database | Log Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace({__name__=~\"^windows_mssql_databases_log_files_size_bytes.*\", instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"}, \"db\", \"$1\", \"__name__\", \"(.*)\")",
     "legendFormat": "{{ database }}"
    }
   ]
  },
  {
   "title": "Database I/O | READ/WRITE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Reads | Rows Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (process) (label_replace({__name__=~\"^windows_process_io_operations_total.*\", mode=\"read\", instance=~\"$instance.*\", process=~\"(.*)\"}, \"name\", \"$1\", \"__name__\", \"(.*)\"))",
     "legendFormat": "{{process}}"
    }
   ]
  },
  {
   "title": "Writes | Rows Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (process) (label_replace({__name__=~\"^windows_process_io_operations_total.*\", mode=\"write\", instance=~\"$instance.*\", process=~\"(.*)\"}, \"name\", \"$1\", \"__name__\", \"(.*)\"))",
     "legendFormat": "{{ process }}"
    }
   ]
  },
  {
   "title": "Database Latency | FETCH/PEAK",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Fetch | DLC Latency (ms)",
   "type": "graph",
   "description": "**Fetch | DLC Latency (ms)**\n\nAverage latency in microseconds between log blocks entering the Direct Log Consumer and being retrieved by the XTP controller, per second.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "label_replace({__name__=~\"^windows_mssql_databases_xtp_controller_dlc_fetch_latency_seconds.*\", instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"}, \"db\", \"$1\", \"__name__\", \"(.*)\")",
     "legendFormat": "{{ database }}"
    }
   ]
  },
  {
   "title": "Peak | DLC Latency (ms)",
   "type": "graph",
   "description": "**Peak | DLC Latency (ms)**\n\nThe largest recorded latency, in microseconds, of a fetch from the Direct Log Consumer by the XTP controller.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "label_replace({__name__=~\"^windows_mssql_databases_xtp_controller_dlc_peak_latency_seconds.*\", instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"}, \"db\", \"$1\", \"__name__\", \"(.*)\")",
     "legendFormat": "{{ database }}"
    }
   ]
  },
  {
   "title": "Database Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Database | Log Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "label_replace({__name__=~\"^windows_mssql_databases_log_used_percent.*\", instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"}, \"db\", \"$1\", \"__name__\", \"(.*)\")",
     "legendFormat": "{{ database }}"
    }
   ]
  },
  {
   "title": "Log | Pool Activities",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (mssql_instance) (windows_mssql_databases_log_pool_cache_misses{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"})",
     "legendFormat": "Log Pool Cache Misses/sec"
    },
    {
     "expr": "sum by (mssql_instance) (windows_mssql_databases_log_pool_disk_reads{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"})",
     "legendFormat": "Log Pool Disk Reads/sec"
    },
    {
     "expr": "sum by (mssql_instance) (windows_mssql_databases_log_pool_empty_free_pool_pushes{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"})",
     "legendFormat": "Log Pool Empty Free Pool Pushes/sec"
    },
    {
     "expr": "sum by (mssql_instance) (windows_mssql_databases_log_pool_hash_deletes{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"})",
     "legendFormat": "Log Pool Hash Deletes/sec"
    },
    {
     "expr": "sum by (mssql_instance) (windows_mssql_databases_log_pool_hash_inserts{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"})",
     "legendFormat": "Log Pool Hash Inserts/sec"
    },
    {
     "expr": "sum by (mssql_instance) (windows_mssql_databases_log_pool_log_scan_pushes{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"})",
     "legendFormat": "Log Pool Log Scan Pushes/sec"
    },
    {
     "expr": "sum by (mssql_instance) (windows_mssql_databases_log_pool_requests{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"})",
     "legendFormat": "Log Pool Requests/sec"
    },
    {
     "expr": "sum by (mssql_instance) (windows_mssql_databases_log_pool_requests_old_vlf{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"})",
     "legendFormat": "Log Pool Requests Old VLF/sec"
    },
    {
     "expr": "sum by (mssql_instance) (windows_mssql_databases_log_pool_total_active_log_bytes{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"})"
    },
    {
     "expr": "sum by (mssql_instance) (windows_mssql_databases_log_pool_total_shared_pool_bytes{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"})",
     "legendFormat": "Log Pool Total Shared Pool Bytes/sec"
    }
   ]
  },
  {
   "title": "Log | Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (mssql_instance) (windows_mssql_databases_log_files_size_bytes{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"})",
     "legendFormat": "Log Files Size Bytes/sec"
    },
    {
     "expr": "sum by (mssql_instance) (windows_mssql_databases_log_files_used_size_bytes{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"})",
     "legendFormat": "Log Files Used Size Bytes/sec"
    },
    {
     "expr": "sum by (mssql_instance) (windows_mssql_databases_log_flush_wait_seconds{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"})",
     "legendFormat": "Log Flush Wait Seconds/sec"
    },
    {
     "expr": "sum by (mssql_instance) (windows_mssql_databases_log_flush_waits{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"})",
     "legendFormat": "Log Flush Waits/sec"
    },
    {
     "expr": "sum by (mssql_instance) (windows_mssql_databases_log_flush_write_seconds{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"})",
     "legendFormat": "Log Flush Write Seconds/sec"
    },
    {
     "expr": "sum by (mssql_instance) (windows_mssql_databases_log_flushed_bytes{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"})",
     "legendFormat": "Log Flushed Bytes/sec"
    },
    {
     "expr": "sum by (mssql_instance) (windows_mssql_databases_log_flushes{instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"})",
     "legendFormat": "Log Flushes/sec"
    }
   ]
  },
  {
   "title": "Lock Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Lock Wait Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "label_replace({__name__=\"windows_mssql_locks_lock_wait_seconds\", instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"}, \"name\", \"$1\", \"__name__\", \"(.*)\")",
     "legendFormat": "{{ resource }}"
    }
   ]
  },
  {
   "title": "Lock Timeouts",
   "type": "graph",
   "description": "**Lock Timeouts**\n\nNumber of lock requests per second that timed out, but excluding requests for NOWAIT locks.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "label_replace({__name__=\"windows_mssql_locks_lock_timeouts\", instance=~\"$instance.*\", mssql_instance=~\"$dbinstance.*\"}, \"name\", \"$1\", \"__name__\", \"(.*)\")",
     "legendFormat": "{{ resource }}"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 113 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Used space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace({__name__=~\"^windows_logical_disk_size_bytes.*\", instance=~\"$instance.*\"} - {__name__=~\"^windows_logical_disk_free_bytes.*\", instance=~\"$instance.*\"}, \"name\", \"$1\", \"__name__\", \"(.*)\")",
     "legendFormat": "{{ volume }}"
    }
   ]
  },
  {
   "title": "Available Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 114 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace({__name__=~\"windows_logical_disk_free_bytes.*\",instance=~\"$instance.*\"}, \"name\", \"$1\", \"__name__\", \"(.*)\")",
     "legendFormat": "{{ volume }}"
    }
   ]
  },
  {
   "title": "Networking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 122 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "description": "**Network Traffic**\n\nHere we can see how much network traffic is generated by the Server.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(windows_net_bytes_received_total{instance=~\"$instance.*\", nic!~'isatap.*|VPN.*'}[$interval]) or irate(windows_net_bytes_received_total{instance=~\"$instance\", nic!~'isatap.*|VPN.*'}[5m])",
     "legendFormat": "Inbound"
    },
    {
     "expr": "rate(wmi_net_bytes_sent_total{job=~\"$server\", nic=~\"Microsoft_.*\"}[$interval]) or irate(wmi_net_bytes_sent_total{job=~\"$server\", nic=~\"Microsoft_.*\"}[5m])",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "Network Usage Hourly",
   "type": "graph",
   "description": "**Network Usage Hourly**\n\nHere we can see how much network traffic is generated by the Server per hour.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 123 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "increase(windows_net_bytes_received_total{instance=~\"$instance\", nic!~'isatap.*|VPN.*'}[1h])",
     "legendFormat": "Received"
    },
    {
     "expr": "increase(windows_net_bytes_sent_total{job=~\"$server\", nic=~\"Microsoft_.*\"}[1h])",
     "legendFormat": "Sent"
    }
   ]
  }
 ]
}